// <auto-generated />
using System;
using CampeonatoTKD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CampeonatoTKD.Migrations
{
    [DbContext(typeof(CampeonatoTkdContext))]
    [Migration("20221011181810_addFightsTest1")]
    partial class addFightsTest1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CampeonatoTKD.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<int>("CategoryId");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<double>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("CampeonatoTKD.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CampeonatoTKD.Models.Fights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AthleteId");

                    b.Property<DateTime>("Date");

                    b.Property<double>("Pontos");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Fights");
                });

            modelBuilder.Entity("CampeonatoTKD.Models.Athlete", b =>
                {
                    b.HasOne("CampeonatoTKD.Models.Category", "Category")
                        .WithMany("athlete")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CampeonatoTKD.Models.Fights", b =>
                {
                    b.HasOne("CampeonatoTKD.Models.Athlete", "Athlete")
                        .WithMany("Fights")
                        .HasForeignKey("AthleteId");
                });
#pragma warning restore 612, 618
        }
    }
}
