// <auto-generated />
using System;
using CampeonatoTKD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CampeonatoTKD.Migrations
{
    [DbContext(typeof(CampeonatoTkdContext))]
    [Migration("20221009153722_atualizandoCategoriaToCategory")]
    partial class atualizandoCategoriaToCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CampeonatoTKD.Models.Atleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<int>("CategoryId");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<double>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Atletas");
                });

            modelBuilder.Entity("CampeonatoTKD.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CampeonatoTKD.Models.Fights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AtletaId");

                    b.Property<DateTime>("Date");

                    b.Property<double>("Pontos");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.ToTable("Lutas");
                });

            modelBuilder.Entity("CampeonatoTKD.Models.Atleta", b =>
                {
                    b.HasOne("CampeonatoTKD.Models.Category", "Category")
                        .WithMany("Atletas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CampeonatoTKD.Models.Fights", b =>
                {
                    b.HasOne("CampeonatoTKD.Models.Atleta", "Atleta")
                        .WithMany("Fights")
                        .HasForeignKey("AtletaId");
                });
#pragma warning restore 612, 618
        }
    }
}
